### ISSUE TITLE
Map/dungeon desync between players

### ISSUE THREAD

**Issue by dcburkhart** [thedefside/valheim-mods#2]
I have been experiencing on server an issue where 2 players will enter the same dungeon and basically load 2 different versions of it. I have personally experienced this on another server with my wife. the only common mod between the two packs that appears to touch mountain biome is jtv biomes, so i am beginning my investigation here. is there any possibility that JTV_B could cause this sort of occurrence?

**Comment by thedefside** [comment]
While I don't know how that would be possible, it's certainly not _impossible_. I know that Forgotten Biomes messed up the Mountain caves on my server, but I looked at the code and didn't see anything that would have affected them.

All of the changes I make to the Mountains are right here:
https://github.com/thedefside/valheim-mods/blob/440458c93ee6be2fd1eac95eedae1fea86e8355f/jtv-biomes/JtvBiomes.cs#L111

It's just 2 lines that add a new location to the Zone Manager. You could try turning off the Mountains Locations in the config and see if that helps.

**Comment by dcburkhart** [comment]
Ah sorry, I forgot I had posted this here.
I have determined that the issue was in fact caused by players who cloud save and players who legacy save mingling in the same locations.
The issue evaporated the moment they synced up their settings for character saves

**Comment by thedefside** [comment]
> Ah sorry, I forgot I had posted this here. I have determined that the issue was in fact caused by players who cloud save and players who legacy save mingling in the same locations. The issue evaporated the moment they synced up their settings for character saves

Ah, thanks for letting me know 👍
