### ISSUE TITLE
Mod License Information

### ISSUE THREAD

**Issue by Morpheus1101** [thedefside/valheim-mods#9]
Would you be able to add a License for this mod please.

**Comment by thedefside** [comment]
There already is a license

**Comment by thedefside** [comment]
https://github.com/thedefside/valheim-mods/blob/master/LICENSE

**Comment by Morpheus1101** [comment]
Im blind as its right there plain as day, apologies :)

**Comment by Morpheus1101** [comment]
Would you mind if if i get someone to update this mod, unless you have plans?

**Comment by thedefside** [comment]
The license gives you permission. I don't plan to update it. If you have questions while updating it, just reach out to me.
